Smallpatches
WeakAuras/WeakAuras2 pull request #2520
Opened 2020-10-11 17:53 UTC by InfusOnWoW

2020-10-11 18:07 UTC, mrbuds commented
I'll review later, i see a naming convention inconsistency with GetRegionBy**Uid** and GetDataBy**UID**

2020-10-11 18:08 UTC, Stanzilla requested changes

2020-10-11 18:08 UTC, Stanzilla commented on WeakAuras/Types.lua
> +
assume you added that before moving them to the extra file

2020-10-11 18:08 UTC, Stanzilla commented on WeakAurasOptions/Legendaries.lua
> +
delete extra newline

2020-10-12 03:03 UTC, mrbuds approved these changes

2020-10-12 08:15 UTC, merged