add tab space setting
WeakAuras/WeakAuras2 pull request #2786
Opened 2020-12-04 21:35 UTC by asaka-wa

# Description

Adds a menu to the Settings dropdown in the Editor to allow changing the number of tab spaces. 4 is a bit big when people are used to 2, and with Lua indenting so much. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-12-06 15:24 UTC, InfusOnWoW requested changes

2020-12-06 15:24 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TextEditor.lua
> +          text = L["Tab Spaces"],
"Tab Spaces"? I think the most common way to refer to this is as "Indent Size".

2020-12-06 15:24 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TextEditor.lua
> +      local spaces = {2,4,6}
6?

Anyone in favor of 6 spaces indentation needs to be prevented from using WeakAuras.
I think the 3rd most common indentation size is 3, but having just 2 and 4 is imho good enough.

2020-12-07 18:12 UTC, Stanzilla approved these changes

2020-12-07 18:20 UTC, merged