Nested groups
WeakAuras/WeakAuras2 pull request #2965
Opened 2021-03-07 20:55 UTC by Vardex

# Description

This is an attempt at making nested groups in WeakAuras.
It's mostly functional with most bugs on dragging and dropping.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Right now, not a lot of test has been done, it still need a lot of testing.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

I think drag and drop part need some bug fixes.
Some part of this pr need more checking, mostly commit `Fix dynamic group in dynamic group` and `Try to make group draggable`.
Also I probably missed some part or modified too many in commit `Use new function that iterates children recursively in places that made sense`.

2021-03-12 20:35 UTC, Causese commented
### 1. 

Creating multiple groups (nested, 3 to be specific) causes the third to not appear and causes multiple groups to be created further down the line (this also seems to happen when mix-and-matching group types or when creating 2x groups + 1 icon)

![](https://i.gyazo.com/34e04f395ea36922955d987d00f1ba1d.gif)

**To reproduce:**
Create Group /Dynamic Group region 3 times

```
1x WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua:952: attempt to index field '?' (a nil value)
[string "@WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua"]:952: in function `SortDisplayButtons'
[string "@WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua"]:429: in function <WeakAurasOptions\WeakAurasOptions.lua:426>
[string "=[C]"]: ?
[string "@BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@WeakAuras\WeakAuras-3.1.9-59-ga6273f2.lua"]:1525: in function <WeakAuras\WeakAuras.lua:1379>
[string "@WeakAuras\WeakAuras-3.1.9-59-ga6273f2.lua"]:1535: in function `ScanForLoads'
[string "@WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua"]:837: in function `NewDisplayButton'
[string "@WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua"]:1413: in function `NewAura'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1105: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1104>
```

### 2.

Importing an a weakaura (create copy) that is identical to an existing weakaura causes the imported children to be displayed in the existing WA's group instead of creating a seperate group.

![](https://i.gyazo.com/6d0789509f0bf0a36ea82042be2dc642.gif)

**To reproduce:**
Create a group with 1 icon region wa inside, export it, then import it again and select create copy when importing.

no error.

### 3.

Dragging an icon type WA that is part of group 1 into one of group 1's nested groups causes an error

![](https://i.gyazo.com/77a990d1054b00d6854901902a3f757b.gif)

**To reproduce:**
- Create a group, then an icon within that group and after that also a nested group and try to move the icon into the nested group

```
2x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:291: Calling 'Group' with invalid target. Reload your UI to fix the display list.
[string "=[C]"]: ?
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:291: in function `Group'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:396: in function `action'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1308: in function `Drop'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1197: in function `SetDragging'
[string "@WeakAurasOptions\WeakAurasOptions-3.1.9-59-ga6273f2.lua"]:1251: in function `SetDragging'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:853: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:851>

Locals:
(*temporary) = "Calling 'Group' with invalid target. Reload your UI to fix the display list."
```

2021-03-14 00:53 UTC, InfusOnWoW commented
SyncParentChildRelationships, GetOverlayInfo, probably needs work too.

Group: region:UpdateBorder probably needs special code for sub groups
ActionOptipons is missing a TraverseData for message_format_
AnimationOptions is missing a TraverseData in filterAnimPresetTypes

OptionsPrivate.GetTriggerOptions is missing a TraverseData
WeakAurasOptions OnAboutToDelete/OnDelete probably needs to be adjusted too.
OnDuplicateAura probably needs work for sub groups.
AddTextFormatOption (twice) in RegionOptions\Text.lua needs work.
GetAnchorForData code in SubText needs work.

There are also a ton of checks for data.parent that should be carefully looked at.

2021-03-14 00:53 UTC, InfusOnWoW requested changes

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/InformationOptions.lua
> +            for child in WeakAuras.TraverseData(data) do
This needs to skip sub groups.

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/ModelPicker.lua
> +    for child in WeakAuras.TraverseData(baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/ModelPicker.lua
> +      for child in WeakAuras.TraverseData(self.baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/ModelPicker.lua
> +      for child in WeakAuras.TraverseData(self.baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/ModelPicker.lua
> +      for child in WeakAuras.TraverseData(baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TextEditor.lua
> +      for child in WeakAuras.TraverseData(data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TextEditor.lua
> +      for child in WeakAuras.TraverseData(self.data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TextEditor.lua
> +        for child in WeakAuras.TraverseData(self.data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TexturePicker.lua
> +    for child in WeakAuras.TraverseData(baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TexturePicker.lua
> +    for child in WeakAuras.TraverseData(baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TexturePicker.lua
> +      for child in WeakAuras.TraverseData(baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/OptionsFrames/TexturePicker.lua
> +      for child in WeakAuras.TraverseData(group.baseObject) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/RegionOptions/AuraBar.lua
> +          for child in WeakAuras.TraverseData(data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/RegionOptions/Icon.lua
> +          for child in WeakAuras.TraverseData(data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasOptions/RegionOptions/Text.lua
> +    for child in WeakAuras.TraverseData(data) do
skip sub groups

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasTemplates/TriggerTemplates.lua
> +      for child in WeakAuras.TraverseData(data) do
skip sub groups.

2021-03-14 00:53 UTC, InfusOnWoW commented on WeakAurasTemplates/TriggerTemplates.lua
> +      for child in WeakAuras.TraverseData(data) do
skip sub groups.

2021-11-14 19:04 UTC, Causese commented
**Dragging a dynamic group ontop of another dynamic group's children causes it to error.**
1) Create dynamic group with a bar children
2) Create a another dynamic group
3) Drag 2) ontop of 1)'s child.

1x WeakAuras\RegionTypes\DynamicGroup.lua:524: attempt to perform arithmetic on field 'height' (a nil value)

2021-11-14 19:45 UTC, InfusOnWoW commented
The Grouping button needs to prevent grouping of a parent group into a child group

2021-11-14 23:06 UTC, mrbuds commented
If i click on a dynamic group "new aura" doesn't show group/dg options (that's wanted), but if i create an aura in the dynamic group and click "new aura" it show group options but they don't do anything.

2021-11-14 23:11 UTC, mrbuds commented
If i drag n drop a dynamic group into an other dynamic group, it error and stick the cursor (i have to press escape)

```
1x WeakAuras\RegionTypes\DynamicGroup.lua:496: attempt to perform arithmetic on field 'height' (a nil value)
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:496: in function `growFunc'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1177: in function `DoPositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1055: in function `PositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1036: in function `SortUpdatedChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:933: in function `ReloadControlledChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1259: in function `modify'
[string "@WeakAuras\WeakAuras-3.7.3-18-g83ae77b.lua"]:2745: in function `SetRegion'
[string "@WeakAuras\WeakAuras-3.7.3-18-g83ae77b.lua"]:2566: in function <WeakAuras\WeakAuras.lua:2533>
[string "@WeakAuras\WeakAuras-3.7.3-18-g83ae77b.lua"]:2667: in function `Add'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:300: in function `Group'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:365: in function `func'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1213: in function `Drop'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-18-g83ae77b.lua"]:1443: in function `Drop'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:809: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:805>

Locals:
newPositions = <table> {
  = <table> {
 }
}
activeRegions = <table> {
 1 = <table> {
 }
}
frames = <table> {
  = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <table> {
 }
}
(for control) = ""
frame = ""
regionDatas = <table> {
 1 = <table> {
 }
}
numVisible = 1
x = 0
y = 0
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
i = 1
regionData = <table> {
 region = <unnamed> {
 }
 id = "New 4"
 cloneId = ""
 data = <table> {
 }
 active = true
 dataIndex = 6
 controlPoint = <unnamed> {
 }
 parent = <unnamed> {
 }
 dimensions = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 1 = 0
 2 = 0
 3 = true
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = true
(*temporary) = "attempt to perform arithmetic on field 'height' (a nil value)"
anchorPerUnitFunc = nil
limit = Infinite
startX = 0
stagger = 0
coeff = 0.500000
startY = 0
space = 2
```

2021-11-14 23:16 UTC, mrbuds commented
You can't drag n drop an aura from a group out of it (afaik you could)

2021-11-14 23:19 UTC, mrbuds commented
I get the following error when i try to move an aura that is in a group, to an other group using the "Group" left button

```
2x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:537: attempt to call field 'ClearOptions' (a nil value)
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:537: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:520>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "New 6"
}
(for control) = 1
index = 1
selectedId = "New 6"
selectedData = <table> {
 iconSource = -1
 color = <table> {
 }
 yOffset = 0
 anchorPoint = "CENTER"
 cooldownSwipe = true
 cooldownEdge = false
 icon = true
 triggers = <table> {
 }
 internalVersion = 45
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 subRegions = <table> {
 }
 height = 64.000015
 load = <table> {
 }
 regionType = "icon"
 animation = <table> {
 }
 authorOptions = <table> {
 }
 information = <table> {
 }
 xOffset = 0
 zoom = 0
 actions = <table> {
 }
 anchorFrameType = "SCREEN"
 id = "New 6"
 uid = "C5qGhzZJLsm"
 frameStrata = 1
 width = 62.499939
 cooldownTextDisabled = false
 config = <table> {
 }
 inverse = false
 alpha = 1
 conditions = <table> {
 }
 cooldown = false
 parent = "Important Priest"
}
selectedButton = <table> {
 thumbnailType = "icon"
 GetData = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1332
 GetOffset = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1266
 Expand = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1335
 UpdateOffset = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1253
 UpdateViewTexture = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1503
 icon = <unnamed> {
 }
 GetExpanded = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1366
 ReleaseThumbnail = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1584
 DisableDownGroup = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1426
 upgroup = <unnamed> {
 }
 SetNormalTooltip = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:977
 title = <unnamed> {
 }
 SetIds = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1307
 IsEnabled = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1547
 SetData = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1328
 RestoreIcon = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1644
 orgIcon = <unnamed> {
 }
 OverrideIcon = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1637
 SetViewClick = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1293
 callbacks = <table> {
 }
 DragReset = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1219
 data = <table> {
 }
 OnAcquire = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:453
 DropEnd = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1222
 SetIcon = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1620
 downgroup = <unnamed> {
 }
 warning = <unnamed> {
 }
 SetOnExpandCollapse = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1363
 IsGroup = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1325
 DisableUpGroup = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1418
 Collapse = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1349
 Ena
```

2021-11-14 23:26 UTC, mrbuds commented
If i make enough sub-groups, selecting any of those groups make a mini-freeze, i don't know if it's possible to improve that
![image](https://user-images.githubusercontent.com/189656/141702861-8477acae-7ad3-4944-84c2-bb7146418cb9.png)

2021-11-14 23:53 UTC, mrbuds commented
If i click on a group and click "new aura" it keep group selected (that's correct)
If i click a sub group and click "new aura" it deselect it and will create the aura in "root"

2021-11-15 00:02 UTC, mrbuds commented
First subgroup is not created in rename mode, same for the first aura of a subgroup, also it change position of scroll bar top move the new aura or group at the top when it should not

- New group > press enter to confirm name
- new dynamic group > it's not selected in "rename" mode
- new aura in that dynamic group > it's not selected in "rename" mode

2021-11-15 11:49 UTC, Stanzilla commented
We should probably add a hard limit for how many times you can nest

2021-11-16 23:38 UTC, InfusOnWoW commented
> If i click on a dynamic group "new aura" doesn't show group/dg options (that's wanted), but if i create an aura in the dynamic group and click "new aura" it show group options but they don't do anything.
> 
I'm not sure what's not working here. Can you describe this in more detail?

2021-11-16 23:58 UTC, mrbuds commented
> 
> 
> > If i click on a dynamic group "new aura" doesn't show group/dg options (that's wanted), but if i create an aura in the dynamic group and click "new aura" it show group options but they don't do anything.
> 
> I'm not sure what's not working here. Can you describe this in more detail?

![image](https://user-images.githubusercontent.com/189656/142084580-36cc4fdc-e973-455a-8864-50f86ca64168.png)
![image](https://user-images.githubusercontent.com/189656/142084655-ab3ac6ee-279a-480d-8ca0-2bba62724eb5.png)
![image](https://user-images.githubusercontent.com/189656/142084811-b48c2a80-749a-45dc-9091-40b29b3d23d4.png)
![image](https://user-images.githubusercontent.com/189656/142084954-5d66863d-c789-4467-83c9-3725e9ac2a22.png)

2021-11-16 23:59 UTC, mrbuds commented
Bug is 3rd screenshot

2021-11-20 14:41 UTC, InfusOnWoW commented
@Buds I have just tested the current non-nested state, and you can't drag and drop auras out of groups

2021-11-20 15:14 UTC, mrbuds commented
> @buds I have just tested the current non-nested state, and you can't drag and drop auras out of groups

Indeed, i just tested with an older version (3.6.0) and can only drag & drop between groups. So no regression there, but potential improvement.

Also tested what was showing the "new aura" panel when an aura inside a group is selected, and it was showing "new group" options, but clicking it was creating the group in "root".

2021-11-20 18:25 UTC, InfusOnWoW commented
@mrbuds New Auras not being in rename mode seems to only happen if they are "off-screen" at the time of creation. I can't otherwise reproduce that.

2021-11-20 18:27 UTC, InfusOnWoW commented
@Stanzilla I don't think we need a hard-limit. There's no reason a deeply nested structure should be fundamentally slower than a group with the same number of auras. Although as Buds experiences show, that'll require a few fixes along the way.

2021-11-20 18:37 UTC, InfusOnWoW commented
@Causese, @mrbuds I think I fixed all the issues you found in your first round.

Noteable, the problem with "New Group" not creating the auras in the right place, was actually intended. If a empty group is selected we show the "New pane". If the user clicked on "New Aura", while the new pane was already showing the aura got deselected. I removed that now, since on review it doesn't work too well.

2021-11-20 18:54 UTC, Causese commented
I get this when renaming a group with recent build

4x ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1032: attempt to index field '?' (a nil value)
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1032: in function `ClearPicks'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1251: in function `PickDisplay'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-21-ga6b8e9d.lua"]:1264: in function `PickDisplay'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-21-ga6b8e9d.lua"]:586: in function <WeakAurasOptions\WeakAurasOptions.lua:565>
[string "=[C]"]: ?
[string "@BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@WeakAuras\WeakAuras-3.7.3-21-ga6b8e9d.lua"]:1951: in function `Rename'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:793: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:789>
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1312: in function `func'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1751: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1745>

2021-11-20 19:11 UTC, Causese commented
issue: removing child from parent and then moving the parent into the former child's group causes it to be hidden when clicking the expand button

1. Create this setup
![](https://i.gyazo.com/78b6bdafaf933abf0bd7fa36cef0b1bf.png)
2. click the "<" in the last child group (new 3)
3. move new 2 into new 3
4. click the expand button

2021-11-27 07:54 UTC, Causese commented
seems like there are few more places for the issue

1. Create a group with a dynamic group as child.
2. Create a standalone dynamic group
3. drag 2) ontop of 1)

```
3x WeakAuras\RegionTypes\DynamicGroup.lua:524: attempt to perform arithmetic on field 'height' (a nil value)
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:524: in function `growFunc'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1177: in function `DoPositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1055: in function `PositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1036: in function `SortUpdatedChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:933: in function `ReloadControlledChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1259: in function `modify'
[string "@WeakAuras\WeakAuras-3.7.3-21-ga6b8e9d.lua"]:2742: in function `SetRegion'
[string "@WeakAuras\WeakAuras-3.7.3-21-ga6b8e9d.lua"]:2563: in function <WeakAuras\WeakAuras.lua:2530>
[string "@WeakAuras\WeakAuras-3.7.3-21-ga6b8e9d.lua"]:2664: in function `Add'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:300: in function `Group'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:356: in function `func'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1224: in function `Drop'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-21-ga6b8e9d.lua"]:1448: in function `Drop'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:809: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:805>

Locals:
newPositions = <table> {
  = <table> {
 }
}
activeRegions = <table> {
 1 = <table> {
 }
}
frames = <table> {
  = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = <table> {
 }
}
(for control) = ""
frame = ""
regionDatas = <table> {
 1 = <table> {
 }
}
numVisible = 1
x = 0
y = 0
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
i = 1
regionData = <table> {
 region = <unnamed> {
 }
 id = "New 3"
 cloneId = ""
 data = <table> {
 }
 active = true
 dataIndex = 1
 controlPoint = <unnamed> {
 }
 parent = <unnamed> {
 }
 dimensions = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 1 = 0
 2 = 0
 3 = true
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = true
(*temporary) = "attempt to perform arithmetic on field 'height' (a nil value)"
anchorPerUnitFunc = nil
limit = Infinite
startX = 0
stagger = 0
coeff = 0.500000
startY = 0
space = 2
```

2021-12-03 18:44 UTC, InfusOnWoW commented
> Create a group with a dynamic group as child.
> Create a standalone dynamic group
>  drag 2) ontop of 1)
@Causese I couldn't reproruce that, but that might be because I already fixed that locally before.

The other case is now also fixed, and I again believe this to be bug free now. :)

2021-12-04 20:09 UTC, InfusOnWoW commented
I accidentally closed this, and gibthub is being stupid.

Continued at https://github.com/WeakAuras/WeakAuras2/pull/3380

2022-01-02 23:50 UTC, Causese commented
Can't reproduce it yet but last thing i did was mess with custom options (add an option then export and try to import while exported group was still there)

```
1x ...aceWeakAurasOptions\OptionsFrames\Update-Update.lua:313: table index is nil
[string "@WeakAurasOptions\OptionsFrames\Update-Update.lua"]:313: in function `handleSortHybridTable'
[string "@WeakAurasOptions\OptionsFrames\Update-Update.lua"]:332: in function <...aceWeakAurasOptions\OptionsFrames\Update.lua:246>
[string "@WeakAurasOptions\OptionsFrames\Update-Update.lua"]:1103: in function <...aceWeakAurasOptions\OptionsFrames\Update.lua:1070>
[string "@WeakAurasOptions\OptionsFrames\Update-Update.lua"]:1172: in function <...aceWeakAurasOptions\OptionsFrames\Update.lua:1143>
[string "=(tail call)"]: ?
[string "@WeakAuras\Transmission.lua"]:456: in function <WeakAuras\Transmission.lua:450>
[string "=(tail call)"]: ?
[string "@WeakAurasOptions\OptionsFrames\ImportExport.lua"]:83: in function <...dOns\WeakAurasOptions\OptionsFrames\ImportExport.lua:77>

Locals:
data = <table> {
 arcLength = 360
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 authorOptions = <table> {
 }
 yOffset = 0
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 rowSpace = 1
 actions = <table> {
 }
 triggers = <table> {
 }
 columnSpace = 1
 radius = 200
 animation = <table> {
 }
 align = "CENTER"
 stagger = 0
 config = <table> {
 }
 parent = "New 4"
 subRegions = <table> {
 }
 sort = "none"
 rotation = 0
 load = <table> {
 }
 useLimit = false
 backdropColor = <table> {
 }
 space = 2
 source = "import"
 internalVersion = 48
 scale = 1
 sortHybridTable = <table> {
 }
 border = false
 borderEdge = "Square Full White"
 regionType = "dynamicgroup"
 borderSize = 2
 limit = 5
 groupIcon = 607513
 borderInset = 1
 constantFactor = "RADIUS"
 frameStrata = 1
 borderOffset = 4
 gridType = "RD"
 tocversion = 90200
 id = "New 5"
 grow = "DOWN"
 gridWidth = 5
 anchorFrameType = "SCREEN"
 fullCircle = true
 uid = "sprypUdMvYu"
 animate = false
 xOffset = 0
 conditions = <table> {
 }
 information = <table> {
 }
 selfPoint = "TOP"
}
sortHybridTableByUid = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 New 3 = false
}
(for control) = "New 3"
id = "New 3"
b = false
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = "table index is nil"
idToUid = <table> {
 New 5 = "sprypUdMvYu"
 New 6 = "46J8D3KV0yU"
 New 4 = "vgGK)R9GrZp"
}
uidMap = <table> {
 map = <table> {
 }
 type = "new"
 root = "vgGK)R9GrZp"
 totalCount = 3
 idToUid = <table> {
 }
}
```

2022-01-03 00:22 UTC, Causese commented
Some good old classic convert bug that forces you to wipe SV:

1. Make Icon
2. Convert to Text
3. RIP SV

![](https://i.gyazo.com/5f5176c4a79ca8509b5c7e69f286d284.png)

short version of errors
`1x WeakAuras\SubRegionTypes\SubText.lua:415: attempt to call method 'AnchorSubRegion' (a nil value)`
`2x WeakAuras\SubRegionTypes\SubText.lua:280: attempt to call method 'UpdateAnchorOnTextChange' (a nil value)`
`2x WeakAuras\WeakAuras-@project-version@.lua:3951: attempt to call method 'Collapse' (a nil value)`

long version would be enough to build a bridge to narnia

2022-01-03 00:40 UTC, Causese commented
Creating 2 Icon type auras and multiselecting them (shift click) and trying to right click one of them causes an error

```
1x WeakAurasOptions\WeakAurasOptions-@project-version@.lua:427: attempt to index local 'parentData' (a nil value)
[string "@WeakAurasOptions\WeakAurasOptions-@project-version@.lua"]:427: in function `MultipleDisplayTooltipMenu'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:494: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:464>

Locals:
frame = WeakAurasOptions {
 0 = <userdata>
 texturePicker = <table> {
 }
 HideTip = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:517
 CenterOnPicked = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1326
 window = "default"
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 ClearOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:883
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 EnsureOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:946
 PickDisplayMultiple = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1342
 OnRename = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1049
 RightEdge = <unnamed> {
 }
 importexport = <table> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 importThumbnail = <unnamed> {
 }
 ShowTip = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:510
 ClearPick = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1030
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 TopRightCorner = <unnamed> {
 }
 iconPicker = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 UpdateFrameVisible = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:274
 TopEdge = <unnamed> {
 }
 mover = <unnamed> {
 }
 bottomLeftResizer = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 pendingInstallButton = <table> {
 }
 buttonsContainer = <table> {
 }
 tipFrame = <table> {
 }
 update = <table> {
 }
 codereview = <table> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 container = <table> {
 }
 pendingUpdateButton = <table> {
 }
 loadProgress = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 texteditor = <table> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 moversizer = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 PickDisplay = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1270
 backdropInfo = <table> {
 }
 GetTargetAura = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1085
 pickedDisplay = <table> {
 }
 SetLoadProgressVisible = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:640
 FillOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:975
 tipFrameIsVisible = true
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 loadProgessVisible = false
 GetPickedDisplay = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1383
 filterInput = WeakAurasFilterInput {
 }
 PickDisplayBatch = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1366
 buttonsScroll = <table> {
 }
 BottomLeftCorner = <unnamed> {
 }
 NewAura = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1096
 modelPicker = <table> {
 }
 loadedButton = <table> {
 }
 UpdateOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:921
 TopLeftCorner = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 bottomRightResizer = <unnamed> {
 }
 ClearPicks = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1061
 ClearAndUpdateOptions = <function> defined @WeakAurasOptions\OptionsFrames\
```

2022-01-03 19:30 UTC, Causese commented
two errors below that are related but I can't reproduce yet

```
1x ...faceWeakAurasOptions\RegionOptions\Group-Group.lua:594: attempt to index local 'childData' (a nil value)
[string "@WeakAurasOptions\RegionOptions\Group-Group.lua"]:594: in function `create'
[string "@WeakAurasOptions\GroupOptions.lua"]:13: in function `?'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:963: in function `EnsureOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:940: in function `UpdateOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:982: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1303: in function `PickDisplay'
[string "@WeakAurasOptions\WeakAurasOptions-@project-version@.lua"]:1191: in function `PickDisplay'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:506: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:464>

Locals:
id = "New 10"
data = <table> {
 backdropColor = <table> {
 }
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 xOffset = 0
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 borderColor = <table> {
 }
 authorOptions = <table> {
 }
 scale = 1
 actions = <table> {
 }
 triggers = <table> {
 }
 borderInset = 1
 internalVersion = 48
 yOffset = 0
 animation = <table> {
 }
 id = "New 10"
 anchorPoint = "CENTER"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 selfPoint = "CENTER"
 uid = "rUtC8BLnQ90"
 borderOffset = 4
 subRegions = <table> {
 }
 config = <table> {
 }
 conditions = <table> {
 }
 information = <table> {
 }
 load = <table> {
 }
}
options = <table> {
 __title = "Group Settings"
 chooseIcon = <table> {
 }
 __order = 1
 endHeader = <table> {
 }
 scale = <table> {
 }
 groupIcon = <table> {
 }
}
hasSubGroups = false
hasDynamicSubGroup = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "New"
 2 = "New 5 2"
 3 = "New 2"
}
(for control) = 1
index = 1
childId = "New"
childData = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "attempt to index local 'childData' (a nil value)"
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Destination Reaction = "Destination Reaction"
 Threat Value = "Threat Value"
 A 48x48 pixels icon = "A 48x48 pixels icon"
 Stacks = "Stacks"
 Aura(s) Missing = "Aura(s) Missing"
 Incoming Heal = "Incoming Heal"
 Armor against Target (%) = "Armor against Target (%)"
 Show Heal Absorb = "Show Heal Absorb"
 Frost Resistance = "Frost Resistance"
 Aggro = "Aggro"
 Alpha = "Alpha"
 Player Character = "Player Character"
 If unchecked, then a default color will be used (usually yellow) = "If unchecked, then a default color will be used (usually yellow)"
 Down = "Down"
 Always active trigger = "Always active trigger"
 In Vehicle = "In Vehicle"
 Down, then Right = "Down, then Right"
 Shows a custom texture = "Shows a custom texture"
 Resurrect = "Resurrect"
 Rotate Right = "Rotate Right"
 Pulse = "Pulse"
 Fail Alert = "Fail Alert"
 Role = "Role"
 Vertical Bar = "Vertical Bar"
 Angle = "Angle"
 Not On Threat Table = "Not On Threat Table"
 Hit (%) = "Hit (%)"
 25 Player Raid (Normal) = "25 Player Raid (Normal)"
 Always include realm = "Always include realm"
 Glow %s = "Glow %s"
 Y Offset = "Y Offset"
 Loop = "Loop"
 Item Slot String = "Item Slot String"
 Frequency = "Frequency"
 Source = "Source"
 Animations = "Animations"
 Large = "Large"
 Can be a name or a UID (e.g., party1). A name only works on friendly players in your group. = "Can be a name or a UID (e.g., party1). A name only works on friendly players in your group."
 |cffeda55fRight-Click|r to toggle performance profiling window. = "|cffeda55fRight-Click|r to toggle performance profiling window."
 Multiple Triggers = "Multiple Triggers"
 %s - Custom Sort = "%s - Custom Sort"
 Cast Bar = "Cast Bar"
 Custom Sort = "Custom Sort"
 On Hide = "On Hide"
 Current Movement Speed (%) = "Current Movement Speed (%)"
 Small Icon = "Small Icon"
 The following auras will be added: %s
 = "The following auras will be added: %s
"
 Block against Target (%) = "Block against Target (%)"
 Add Missing Auras = "Add Missing Auras"
 Automatic Icon = "Automatic Icon"
 Overlay Latency = "Overlay Latency"
 Contains = "Contains"
 Inherited = "Inherited"
 Player Effective Level = "Player Effective Level"
 Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations. = "Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."
 Column Space = "Column Space"
 Parry (%) = "Parry (%)"
 Extra Attacks = "Extra Attacks"
 Timed = "Timed"
 Ungroup = "Ungroup"
 Remaining Duration = "Remaining Duration"
 Negator = "Not"
 Cooldown Settings = "Cooldown Settings"
 Raid (Timewalking) = "Raid (Timewalking)"
 Only if selected = "Only if selected"
 5 Man Dungeon = "5 Man Dungeon"
 Icon Inset = "Icon Inset"
 Player Faction =
```

```
6x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:966: attempt to index local 'childData' (a nil value)
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:966: in function `addChildrenNames'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:971: in function `SetNormalTooltip'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:804: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:799>

Locals:
data = <table> {
 backdropColor = <table> {
 }
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 xOffset = 0
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 borderColor = <table> {
 }
 authorOptions = <table> {
 }
 scale = 1
 actions = <table> {
 }
 triggers = <table> {
 }
 borderInset = 1
 internalVersion = 48
 yOffset = 0
 animation = <table> {
 }
 id = "New 10"
 anchorPoint = "CENTER"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 selfPoint = "CENTER"
 uid = "rUtC8BLnQ90"
 borderOffset = 4
 subRegions = <table> {
 }
 config = <table> {
 }
 conditions = <table> {
 }
 information = <table> {
 }
 load = <table> {
 }
}
indent = "  "
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "New"
 2 = "New 5 2"
 3 = "New 2"
}
(for control) = 1
index = 1
childId = "New"
childData = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "attempt to index local 'childData' (a nil value)"
pairs = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
namestable = <table> {
 1 = ""
 2 = "  New"
}
addChildrenNames = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:962
```

2022-01-03 23:00 UTC, InfusOnWoW commented
@Causese I fixed two of the issues.

The convert bug is not caused by nested, but by some changes in the latest alpha. I'll fix that separately, though it requires a bit of work.

The latest bugs, I couldn't figure out just from the lua errors. They point out that a group thinks its the parent of some children, but those childrens don't exist. That sounds like it has something to do with a changed structure and either deleting obsolete children, or not adding new children.

While investigating, I found another bug in that area, which I'll fix in the coming days.

2022-01-03 23:15 UTC, InfusOnWoW commented
@Causese I might have found the issue after all and fixed it. Thanks so far.

2022-01-04 19:49 UTC, Causese commented
3 errors below that are related. Can reproduce by following video steps identially but it's awful
https://www.youtube.com/watch?v=LzbwBsFpq9M

Tried to reproduce from 1:57min and onwards and it didn't work so i guess some earlier steps play a role

![test](https://i.gyazo.com/76e4b44f345d9dbe1cef8c8a6de49eee.png)

```
1x WeakAuras\RegionTypes\Group-Group.lua:102: WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua:5208: attempt to index local 'data' (a nil value)
[string "=[C]"]: in function `(for generator)'
[string "@WeakAuras\RegionTypes\Group-Group.lua"]:102: in function `modify'
[string "@WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua"]:2773: in function `SetRegion'
[string "@WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua"]:2591: in function <WeakAuras\WeakAuras.lua:2550>
[string "@WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua"]:2695: in function `Add'
[string "@WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua"]:2703: in function `AddParents'
[string "@WeakAuras\WeakAuras-3.7.3-59-g9a88083.lua"]:1868: in function `Delete'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-59-g9a88083.lua"]:447: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5148: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
 = <no value>
```

```
2x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:966: attempt to index local 'childData' (a nil value)
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:966: in function `addChildrenNames'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:971: in function `SetNormalTooltip'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:804: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:799>

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 authorOptions = <table> {
 }
 preferToUpdate = false
 yOffset = 0
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 48
 selfPoint = "CENTER"
 subRegions = <table> {
 }
 load = <table> {
 }
 backdropColor = <table> {
 }
 source = "import"
 scale = 1
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 borderOffset = 4
 tocversion = 90200
 id = "New 10"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 animation = <table> {
 }
 borderInset = 1
 xOffset = 0
 uid = "S667pc4F2Nx"
 conditions = <table> {
 }
 information = <table> {
 }
 config = <table> {
 }
}
indent = "  "
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "New"
 2 = "New 4"
 3 = "New 4 2"
 4 = "New 2 2"
}
(for control) = 1
index = 1
childId = "New"
childData = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "attempt to index local 'childData' (a nil value)"
pairs = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
namestable = <table> {
 1 = ""
 2 = "  New"
}
addChildrenNames = <function> defined @WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:962
```

```
1x ...faceWeakAurasOptions\RegionOptions\Group-Group.lua:594: attempt to index local 'childData' (a nil value)
[string "@WeakAurasOptions\RegionOptions\Group-Group.lua"]:594: in function `create'
[string "@WeakAurasOptions\GroupOptions.lua"]:13: in function `?'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:963: in function `EnsureOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:940: in function `UpdateOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:982: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1303: in function `PickDisplay'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.3-59-g9a88083.lua"]:1191: in function `PickDisplay'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:499: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:464>

Locals:
id = "New 10"
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 authorOptions = <table> {
 }
 preferToUpdate = false
 yOffset = 0
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 48
 selfPoint = "CENTER"
 subRegions = <table> {
 }
 load = <table> {
 }
 backdropColor = <table> {
 }
 source = "import"
 scale = 1
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 borderOffset = 4
 tocversion = 90200
 id = "New 10"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 animation = <table> {
 }
 borderInset = 1
 xOffset = 0
 uid = "S667pc4F2Nx"
 conditions = <table> {
 }
 information = <table> {
 }
 config = <table> {
 }
}
options = <table> {
 __title = "Group Settings"
 chooseIcon = <table> {
 }
 __order = 1
 endHeader = <table> {
 }
 scale = <table> {
 }
 groupIcon = <table> {
 }
}
hasSubGroups = false
hasDynamicSubGroup = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "New"
 2 = "New 4"
 3 = "New 4 2"
 4 = "New 2 2"
}
(for control) = 1
index = 1
childId = "New"
childData = nil
(*temporary) = "New"
(*temporary) = nil
(*temporary) = "attempt to index local 'childData' (a nil value)"
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Destination Reaction = "Destination Reaction"
 Threat Value = "Threat Value"
 A 48x48 pixels icon = "A 48x48 pixels icon"
 Stacks = "Stacks"
 Aura(s) Missing = "Aura(s) Missing"
 Incoming Heal = "Incoming Heal"
 Armor against Target (%) = "Armor against Target (%)"
 Show Heal Absorb = "Show Heal Absorb"
 Frost Resistance = "Frost Resistance"
 Aggro = "Aggro"
 Alpha = "Alpha"
 Player Character = "Player Character"
 If unchecked, then a default color will be used (usually yellow) = "If unchecked, then a default color will be used (usually yellow)"
 Down = "Down"
 Always active trigger = "Always active trigger"
 In Vehicle = "In Vehicle"
 Down, then Right = "Down, then Right"
 Shows a custom texture = "Shows a custom texture"
 Resurrect = "Resurrect"
 Rotate Right = "Rotate Right"
 Pulse = "Pulse"
 Fail Alert = "Fail Alert"
 Role = "Role"
 Vertical Bar = "Vertical Bar"
 Angle = "Angle"
 Not On Threat Table = "Not On Threat Table"
 Hit (%) = "Hit (%)"
 25 Player Raid (Normal) = "25 Player Raid (Normal)"
 Always include realm = "Always include realm"
 Glow %s = "Glow %s"
 Y Offset = "Y Offset"
 Loop = "Loop"
 Item Slot String = "Item Slot String"
 Frequency = "Frequency"
 Source = "Source"
 Animations = "Animations"
 Large = "Large"
 Can be a name or a UID (e.g., party1). A name only works on friendly players in your group. = "Can be a name or a UID (e.g., party1). A name only works on friendly players in your group."
 Multiple Triggers = "Multiple Triggers"
 %s - Custom Sort = "%s - Custom Sort"
 Cast Bar = "Cast Bar"
 Custom Sort = "Custom Sort"
 On Hide = "On Hide"
 Current Movement Speed (%) = "Current Movement Speed (%)"
 Small Icon = "Small Icon"
 The following auras will be added: %s
 = "The following auras will be added: %s
"
 Block against Target (%) = "Block against Target (%)"
 Add Missing Auras = "Add Missing Auras"
 Automatic Icon = "Automatic Icon"
 Overlay Latency = "Overlay Latency"
 Contains = "Contains"
 Inherited = "Inherited"
 Player Effective Level = "Player Effective Level"
 Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations. = "Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."
 Column Space = "Column Space"
 Parry (%) = "Parry (%)"
 Extra Attacks = "Extra Attacks"
 Timed = "Timed"
 Ungroup = "Ungroup"
 Remaining Duration = "Remaining Duration"
 Negator = "Not"
 Cooldown Settings = "Cooldown Settings"
 Raid (Timewalking) = "Raid (Timewalking)"
 Only if selected = "Only if se [...]

2022-01-04 20:15 UTC, Causese commented
stuck on update after the following scenario

1. import
```
!WA:2!DwvZ2nTru46ksPi4qtmqkqtPPHcTLwstJBcj0)WYXgsXyhKvi0vjJKgBnezjXmJItY50f4dhozTFe86UYpc5j4E8I(aKhH8e07ijh(zrBpDZOr35EN797(Z3K7j5frtuy27mBHBVWY3U1YKLwAULkKVDE38UhCTH2eNTD5HrLc9d5)MMM2AAZn7cr5DcdK8qFFQBjpMVlNgClZA0otxizD(JSd5UuUrM1rJB4Z2FFc3DARWqFjlYu4q8PA2P651p9Bz3w0OjA88ycNoDLyF)P3WJjP950wSWaR9IOMT4HXrzQ3GTpDS(YqNDOCbQWLZT1thKEuA8MlxoTbKahVq(AHSaPDPY1SkBY3TEZMcQmhN4ir7elAkKeUu3UjlGj80nWps9UsoRvl8QV6n5zBFvFxQDCZMQqH)GYvxRY6vnKQ4IeZjZ3ver99x1vOFKi2MUdnq2a1MT7GnlvSH1MnSkAAzeJxUDKpzpk3mG0Mk0ntu1(buIV07etxJtrtnBSw5Qv7fhKfc689YI(Jrer5be)NKcFIHFiXTITeZSbYjnBhJzADdmMCMeUTUPJpriu7meyItTPhjG1MOsblcxQYHuIG2qI1YwsVtdtzeegqh6IatPXMkyYfuSY7k6QuvLeGcgTjSGkW8Obqb4hGfGfXVt(UsMH5op2AmKelXQr9OK8U(GMCmbG(KijAhNwPQOePUB7gLmlxU2HPv0uqFgB0)nzT0ZQZRgGc16JPmZKEeHEpb1Vzs1gY3xfSSmxXcAgYtrR(8Xm3b78WWnwzHLwHU9tY7CRdUEFgQEJWyUdDQ3dUqo4RZbta5h6GTSUHDcA0Hfr36Wr)QAw9mu2SfC5ZFt4kVcUk8jiM)u4A6WNbtdFomdCDD4lGBa3e(s4R0JMq1WTd1kTu(Oqx6F(EWTihVnLgvuvOKMQa0dkIbVlvqKQSp1dU3DNeMAict1aPAgiW9GlgLxs3vUPWJGXZtZ6kIUsIWKLuaVPiBduO3jNnZnerJ)gM)6bMJsLoklAuCDR6rxiriw8cvzqNnyUspJI4VhN6i2Uu3eHVyyAv83ZcNdto)zXcjR5EiO4HseqwOqJA1RvgMIJGsPt)efDgXZO1ldbbYOXRWz7p9JJjUQ(KPTSElGpYtdtK1bBl2GtI6Ur2M0ayhMGz7t3kdZVbNq0eRwRwzZnnQBzv)rMRE)hyn8exRyyUsgIE6B5h1PjSa1x3Q6Q1k)xdB5h2PcN(8yAGZERDQ5MD(fsrN6GbQLr3qx1pkJhAhlLHb1r(lKoOVsC1KPVlLO)iK1t9ZjmWAhglO3FKepd1HEjE3YJ5SDavi0sSOrcfBY2Qmu8ejoWiLX12JYA5jFb8nvGVvXfaZMS(DjRZLSEoyvZojfv47veeV7q(D(3h7Hs62riBoonUKX(HHTZbxeVkDysD4J1HpsrzJudWPmFDLhURg8JWpbRmOnLSXJFyPYDA3e(fDolqr0t9IU4OzqvF0kmbblTUEMe)ipIgyO3D05EWY6hmxpc3jnV(YjbnD4dGtd7blLnFdJN02BkIio0XERW7Yx9)0y9am2JBh0qDbA2CIllw8YZ1fltvzTzsvGXAfa554RmQ5(CW90)NY7V)jp0A6RUGZYt5PrEGpudtllU8ZmAy94MZvyj4mEGoCw4Ch6Uh(wcZj59r48Jzic54apuCER6R1nzQdj(YHKnyk5iK0cJLazfKpkKBBwCLvxVbMIHF(mOUDsrYRRoJHLKET4S0r8ZQQoDv)Q6HNXCf4x1mq)2XyL6Budjo73eF6UeJ7GdCy1a7b(F3)KFNt9h)n
```
2. duplicate the above
3. put the duplicated group into the imported one
4. import the initial string again but this time pick update
5. untick remove obsolete auras and import it
6. be stuck

```
1x ...aceWeakAurasOptions\OptionsFrames\Update-Update.lua:526: GetIdFor for unknown uid
[string "=[C]"]: in function `error'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:526: in function `GetIdFor'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:1565: in function `FixUpNames'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:1576: in function `FixUpNames'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:1576: in function `FixUpNames'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:1472: in function `ImportImpl'
[string "@WeakAurasOptions\OptionsFrames\Update.lua"]:1393: in function <...aceWeakAurasOptions\OptionsFrames\Update.lua:1392>
```

![](https://i.gyazo.com/dcbea733c6b2c193001b613dcbbc1a27.png)

2022-01-13 17:02 UTC, mrbuds commented on WeakAurasOptions/OptionsFrames/Update.lua
> +      print("Mapping ", key, "to category", category)
debug print

2022-02-06 18:12 UTC, InfusOnWoW commented
Reproductions steps for:
 https://www.youtube.com/watch?v=LzbwBsFpq9M

Import: 
!WA:2!LJ1AtXT1z4Sv2nfzxxGytJDtBOU2oojTo41gWKgMueSlSeXUyTcd2tBbD5SRKrijFKwGL20wtDDPxsVqVKMPnjE2jZKz6LjZSZK)a8l4D4d5hG)j4V1V13Zrs7Yc1bNfpt6LpSA1E056ZZZ7Z7R2uxR7G0JrwU7L62SBZnEw)Un8CdPEooeZrTSDmPe3jtNNSIc(P3lt5x7nn)709M((6EutcvsZyrtQNVFNso2RTMg1SxvppNqB)T1QeA5rl4hA75gisRwOuPasyQ6AUgy7t7z7gQpAM8QzuQhnxJ654rNmvQucund(OgqjiuJgkQxY21oWsuc)kuC9qQD5YeAWPohn(27wZKOxPuj1Q(e6ezKNo7mYsH4pu0Qq1sVEGpXXjNzG49dQOtwM4gwe7T9Q1NF0rkQoFr1ruuLQGtUUVJwvcTr3MMsWUPuC6mYYk8w0NGO5eAP4QTejqCZkUXBbXhGhic1vZ5A4wd39KndioL4Nt4O1WjuHuMdfsoEAMz1d1CWPRhLLQGWLOeUfn6boVOIHJwqa7oPa71iSB2wpgLJqibbHPf67c9Rh4vHAq0TxY3JgQeyGtOGEewAvl67mMLj(Dv8wv0OKEZwXXP3zTSdj1O89cdUukt9Q4h39I4kE4TIUpIV6OwONXYrNONo18)ZtBBQZKaxSV6LOieumKQfQj8GiwnlRj2SQxCuLmzYhZS5CXzsiDfBZ6xjCCVvVQsHlPED6QXsIn1CTxsJX4daFHSBr0cytlXTCO1tc9i5Iy52MipY6X8mwLgqqXQzW6SUYwoqsAjnB3SWi4aajyuymid(DN7ULASXzhjjRB7wYJgTWI64dkzxwSBJ711g9cFMtXL9PHNe(CqhIGyk4iWrHppxEchd3NIqxIqNIq3N6CWtDx44WjW15lcpTiCs4uWxcEg4Rkcpl0l8LHVcCAr4RrGZGZWzfHZLfErgTcpp)6lWV(C8RF9gKl8nGlaVKa0NfCrinCj4Yq)hggOdyWywaeGHeGxg(Mqor4veGHRRnwPYxEqtVbgGaFlgsYp445pbnYUNw6CpT8QPGXfHje19rfdQCVYgP3uJAiZzJ70tcWCPMaZ6LP2Mms40kJfdqkb(AgKdhJtDYHQhooXaigqH41PfRB45uzj3ISjqqNQzAxj4ohn(8Sl2n7(Z3kAo2LDHJsrJewuAkKauCSxYo8imE452dp8I7IhOrAtIfJqwVsarMnylg1GmAc7SLzv0pW2GhlHeLuagrI7czKLotA1ctJ0J0ytUSwvtVfZnY6uVqUSl19rzhU1CdZIwEEuDLrgl3mfzuks1i)2GTNehZkrOYMmaFwBZqRJW4FjCrxrAScZMNjdE1upGT2tuvNXkA6oOdsERALWq)rTPgoKfI4xMCEJZuZgx)ICBKN5jumsSxeI17BBGE5MER4wCfBFYcBL8tMRIvRS7XEKyx)Uyo7ltuJ8mNYZK83FceiFWIeI)imlWqfgWyXIvqp9aTqwCpUyN9L7b6zB0fL5fYGzxZnoUF3HKvdNpWsd3vZf7M4FsEJ8lrX3ZheFdiTzJND6Zg435ogEZSp3pQ1eZBPrMrTG)tXBeZP5Xmmm4WV0i4pFq0czVkjItU92rwHxpE7Sf)53SsqODPQ4HIt9evSrP8fYNb6HIhkwFQX7ytoyZ4tGBOFNzP2R17vROzYmB7vvTLdEYkTnVTvqh3zPA(RpB8nrBGLTdSrXWcXN5DKe2VRC5ZNrzEPcQQfMsj34tOUDJLMLq4KXNO5AzDypLNUTWmQY5YN5J2USJ3kzPKBvH4AuD6d13fs3F0PJ9G6SljZW6SFWg826vcd9ClGjyW8U1ynh50CcE)tozBY(rJKFcBHHHJN0ILe7Hw8vx1Y2yrxsqGaFef5ze53kBJn3fFbKIsqQBrSlBfE7poBaMh8LKyXimRU3CbmUX)4jbbmkCm7awiMPL0AEElLI5E2iInpgZxyUrN4QZiFJviQy0SYkCbsSPn12LLxf12YWKOpLVLMagBUEY8B12MES8xVa3MEq(1(5M14E7FxwSprUZTMfB)Dp3)SyhkjlgcWrjYA3tnc33y8PgVFTP1p)vxo2LtgtG1iB(v(4WHpLZM)Uj4GmcjiqmCDD71SUvUzhAUrOTF68xrigi6qCJ0GgONGfdTdSaR789SaZfGPBRu2Wvfafmh9zGBafrq5BNAF0h52d0CT2xSZG1zTAISZXq2RJTZyyeflt0NAYbdMAYldZCeykSeMVd8DzGnI(fyLS0GcQbZlalWZPMinq4RdMi6DzeEeqQMAJZay2sO0oZucLxaSSywepIzcbBEIp4M8uDWIXz4aNnooGgjU4bWdtrb(rBKBbuiacHk3gwofScoIvHQy3xd(ErBJVp86Wpif8dHFeC7fG1HFmCNtc)KuWDHF6hbBK4gd)m4NNc(fWVeEJta)QuWVoAW)gl43AbBka)ob433f8hSG)4(7lcVzlIfeAABk8TfG)Kf8NVDtU49yIKModdx3)MzKwDGQPVy(IWFHzzwdElEPQVJfQIBvBpWUIZrL98TxyESYg1xnf2ZCKhXyE1uCGQTJDBTeZMcBepyYyuBgRszcAwWhQOr5Bdm8Er67MVLWW1ngA10teuS4QoECJgmY)9TyH9rA7RzfRTBIDr66wWUJ9OHDFAjWrX8Ee4OOhf4O6EZwf4pmwmrGJXZTn9Hcte6rrASrrdE59zCXBhXkOSF46JtSETm3QOrbhZiT99yXcn8TzzZ5)Tldg)3V0)J53lTTpIp(s)D4ez6W1VoTsvnjFt7bSIEHgU(bHSwZOZrIReJe)NzTn)1KdfEmYXOYdsTntf03SvD7l3C3SzTnhg99MI)s5C0yOw0fyS9h0Aw9pXEFheTbZWun1(irqh1DaOxJ)s2CRmexLr8BVMFntmZm8rENz(HUEiUp)oIX(hT49Hw2dx)5ZoQVTC(ZVQPmxPGM6mV9iSmNySZNmo0h9u6)VNJ3bXUd96I90257b9bi23VHvqA5(0ZOokJtq3TOY9r3o0im2GmIj2HuTv19aXQBu2hlVR)ySOv19RO12o0Dhc8zJe4Og5L4gB7vEJbe8e1ZDJXlKFWXU85LtZGQhwjR)TDuYkkYJJk2Hp4(Kx))ZQxfvMnuyrQLyPxSYTbUwpofnkuLrqE46bYgRoIm1COXhIjA7GxCAu1NT9BPNuZkxDFPwYKHI7p0kHdpq(3XLU2EoXhKsxriAVYBmCf1OSGAmn(dX6(ZUBR7C8)SsEKAtdBmHyPIQEthoM7sfJv3nRh6ayD32N5)70VhdjENwRVh18VvR)twFiI2LZo4IVwP1SUEUvsQDvgPQip8H2Lho6q09Yh61)x


Update with:
!WA:2!fBvx3XTrz4kumHiBcXBtmnjLwtcn0uFW4Uj2PPPTul7D9hSE3nALJDdCQT(y2vtSSK8ijV2gkGxcbt5RYsboukNdN9AUA)j4FbVN9I(di)eYDChVZiTRTtojnhZfCJwTJgP595J55DKUtMWStt2mZ6zSZyV3R0X0WAnBMFWu(U(S5LLLllp2OJhKXY3lI576sSNYH6AZiEVHwrs9HVU4A2hA6ZSjm103o4mQU0D2XGzpSUVVBenGTvPQvdjrsMjZ0PvYV5SRrcgSYgXgmYW5JDDhEjhAePfJuJ67PVDarRgZpoiD6vO7q6RvKV1MewioHxsAL)t7KhLuXsssYSTtxRogXro(Ssbr4udvygwIBMqlmYGfPOs9OrkMvXFcDuAeXO1QHF2lCfw6TpOLnXmUAvEzWMnxHY5xSGAeVMmIzgzBegqCDNZou5HHXMKnjErvWzt3Q9ktnzf9vQOpPMUAmUiMbUgBty9MwzgbNMwLY5kuqtmI5Sed3ihnpJ1jHknJ9slbL2gEwigk7tXjnvUI6502pbWjG8uzJP2TnMUATRFdB)jMG00WJUUbhOtaNnpCrvpFpY(eJqsLiu2Qf5CYo2y5ZNXkCWWcjO6Ah2GphouHrvx3G6HVlmk89pjmg8Mqw82HE8rUe1olk)TPEv9zjRPs7Qmec4szezi)OKIppFi(x2SYuA5Yv8riwimpd37KOIetSaQsRP0mK4wvav4QTqYst4ccvsL458qal3IxT0ejv113WoVAiAlgsB9y0PPOIQI1qWKkAwUgHH87mJmCrowmyOfEVCgRpEVxf(k9m4GCID(gIRJdFv4Kqoz4BW9xWPCafOF41HRcNUp4RjbNryZmdqplwPxhgucErKSvGHuGZPaFZlCf4LEaCE4ciF9YW3sbEf4vHHHVnCff47aVgCj4YW3vbga(6Wnjqgf47jKkKy58Bx6(ApXid94JGcaCc4TvGjKHBaVf8gNcExz4hKhMMJvqvCDkX13xC9DuGBHW49uGXvGrAF3zwyMXnkB(63EZhJoUGGiElbrGi(iebVUrIyK2M0DC2yULU5YtYs5eywSE6rhNtWipD6GZdC(aPfKo48lshiTJLihz55i59FcKKGTdqmc)mcKLWIpMP9AF524u64DL3BmvmSPU60LwQyxk4MDPaevyf2QkMrnfLz5swvlmWWI03Xr7BB57gVUxf(hqMJ6JRdqZWLwZdUAdMFKydOeNjEgoGdeznx660O(zj5fehK5nzg204W7pqpPEF7TXijQLiegvD1qFwemAJ4qsb(R7a3kREPYOUNhfIhIBnXSvVO8yuRpZuBYPNBXkCNsnI5cZFJWfM)6OKHfB9uOlmwCXEEurBwJrTxIAh50pxCBW)lp24sAtJQttdMvbra29hIR4PooH4XWvLhxkT3LBrXIOIFmZI8YVWbcxhlSrKTFDVk1PbKv3V7F5nGCoQeE6NljmyqE7Knj6jb1l4Bt(3VakLpAncjysEiuKgxrC42zSrsOrep1fxS35ThcUyhmEJ3SLtSE27D2GmrKTIwj0XaRQLtBGfCEXGIljrSReMEdmAZEp7sVwyWzo0RFqRWhMmA3uv1jxuVuWlkge7n6ZZSTeeU6K4FFuYcr3IKOc72jj)(dslN9fp)EXHr0QBJGs45i64GQflvmhCrgck(CAjMOv3Zqi3mfbErbNjpJUZW3o2WM3HyyD9Ja8URuhXy1Xu)Lygbnwk9MKcytAi1e3)LI5d1GmyW5kwmN2kQL01lTG2CZmRENEln)SdNpfrlFK1H)urp(slQxyUI5(Io1C9RNNr2iM4zTD5tm2OzhpbD8h0MFP7xOb)p8xUJzCuKVxj8KjyZ(w8HtCRNtm)UiRj)p9oDL8(4gPz6oIJk)HoIvx3HATMhjmuw8gveTTe3wGIdpOybutolLPdHwZjA3N1((bu57l47B(0v5PDZcZRUJV)6sIy0EBdlQDGQH7i1Ql8b4o4G7LtDRj2o7BwScUrNr94NadnZ)peCf4yW3(2O7wrNGZ29wUNAAAObkZ2o7ngyGB5tdKNqeiJ4izFnuAvOCFhRgo3wK8(boGg(zm7gC(0A4COUJ69dlYJlp(DC61jDjEN0LXrUfC3UjAyMvbyb4hb)yE3CSd3Q8aWEs0mWk93T93hkJsJ1n3k7SHvQSLRpVziVfCfP0MA35(dS3Lblmj8VMOPPSM9QqVyVuw70pFSwvrkhutKRboPXzaDVZc3tcwdHIlMhbRNGfpWhcGna2UqOeGhRdIHnXPxh2kPE2g2b(jsWpf(i4NTk8ZHFbS75HgsWVeU)xa)QUB9Gha)Ehyp43aF85GFRe87sE5FTe8hCGprg(JYWFAqOPd8N39zPHdaF6XxZql3)Wbz3zG)Ie85ohii)tUI9zYWFBxo9ps7zio)WCBuXQKRn83De60eP9PWnFh1nFnHBE2KdrYfMupq5J1Xk4wAuXFcp9x(HboWtpsB1PNFtJTT9xBUjFkgv0ELCWvUhfXm6r)Wd1lVpoExr0dpX7I2yUJgPjC3AcrCCZnsDZ96RN6KXqTNZ(2)FZaJM1NWaJMA0aJU3p5Og4NAkoAGpSV44YIjDa6J7K)SdjC)RUPetiCZJ0U0Ytn7TxSWDRt056m6M)8ed97j2mKrjZMN4J(Vd


Expand Groups.

2022-02-07 16:06 UTC, Causese commented
The way updates are handled seems different from live.

1. Import 
```
!WA:2!fwvZUTTrq4iWMMuMFQTCIBsAARHbsAtlGrGdsCqakqnTLSDQIKYs6y3Crzj5kYTHIl9UlTS9TieeKZ6rqN7j9i4NGbcf9bWpc(wV1Dxs58ZLEz5SZSZoZ3oFZWkVOQa9GLwzPhxTx1WQHVFPHyEqdsAKm(TZFIpJhs4o4GxhYzzzZ4Kqp6impCbpglrsZ4h0QBxbrwHFyPWyCAqmJ3MrtL(RvRPxn0OU5jjRr5bjKxHez4aY554ajLLkEesiXCPTFxAkveB7O(iThi50OicxCR7YlfF3OqIFE3UEhMr4BwRr76B3WrQ2GW5C8YdezKKKTcf2NiY9j7tsLUQttpyCN1w11RJR3QipNC1L7NLGpKWrP4EeHnYCu)nj4ez8zU2MtuUICBxRrJH5PLPG94awsEVuxncS854qAU4TxEqUG0G2JkJr4eAukCrUctAhQmsDHisKgO2ojmCyDFjorfG5r9YvpF2oQ0oyE4NSrbjyHql5iOhr0ct8lF1xJLW4p1YYQT19x6Hd4S(fzahNs7HLKyKiqDRw(ffR4rfFRfgrYM1DVCmNSqDvfyHDIPsYiUjH0VJhhEO6vGgeXz5zLE5QI(5DemU0jLLswoNgogVY2R0A3nOVKS5qbjPRP2USxR2QCrI11XkNQ0q4P4KxOQAkfKtcuGwItL1vvAg3hT66BTT7eCUuroALzk(2hxeZcMZx5RCPlnYEKKfSFX1CJkD(3fPHl3K0FCxUQI5k5yj2AyeNgUdnugFPtl4B11w1GY3DnuTAnhOpHE)IO1hxeMTsvrXcLORvxYrb6(oR3ANMLwlELRuPI1ivEeslYWX00UmEpdiThw8GReFeC56htWcD(yAvUamhSYKqfvuBUJMyYfe9fjgOpNotGvC6HPP1bK50Gl4bBR(ELpxt1GB9(fhrvE7YY5bKBFo4lRaxaU4KavxxiRFQBFAg5vhpDRUuh7OD4vWxF17cZ8oywOQ6kVgCDByE4BGBzdFh89W3c3gUbCt4hSZMv3bUpXRGB)mwi5Voh8RKtFnHKTQMwkrASedpbUOQ3tGLAWrIH78K5H5MOy2A(PM6Kg((RLvvsoq2reJv5ZULJcYUPrPzP4vSJOuawz4z2w8oISz(i3)qL4KcTtPCoRUTxRS5mkvejMUweyyboRQ2EArGOhqkOgVzsb14pktNJn2)ZCHK29qfOmKxINsPtZwnRbZXvGsFMrMdgmTTZAyjcsLzZuNtpAHNNJd18Wf88(eGpnstm66R4v7WXzd2PuOib2NkO(QjHLy(JgxMn7wnBwd1XPLNxRNH2AJn9MCwO1nM3Ser7(jXrB1mwS12En2QzT)zsucRFDozVCsAWHT)I7V0YpSaDAdJ1ltVHb6nANN4NlLS0wQgp18XrA1f)e46MZpfzd1BoBGK1XQzFBmvtSJ2ySj6EX0GxNseclJhUMbugXguL6znbWPyELFmHgflFdC36WpQN8b3ZS(ZM1FXS(a4LWLuDD2WvSHRAdpx3b(5nsV4)V1cABd)MTZrmwVkQX1zXylyTYPmi1uMfwgE84ODV3tJ37EbR3(3HAwO(gYe6d8bWXMtt1JOiXzxBAtOMiTovGv12WyydytOL9GPgJHZxP6()9U)3d
```
2. Go to trigger and tick something (Name(s) , exact spellID or w/e)
3. Import the above string again, pick update
4. Notice how the triggers remain ticked

2022-03-27 00:24 UTC, merged