Update general layout of WeakAurasOptions
WeakAuras/WeakAuras2 pull request #3700
Opened 2022-07-16 20:04 UTC by mrbuds

# Description

Modify WeakAurasOptions to use PortraitFrameTemplate

![image](https://user-images.githubusercontent.com/189656/179370133-96fc65df-3111-45e5-adbd-4a3b7c0a1f59.png)

## Change
- Couldn't make only title bar move the window, so any non-clickable element can be use to drag the whole window (good? bad?)
- Background is opaque, but dragging window change alpha of the whole window

## Regression
- Removed minimize button (for now) because i couldn't find a proper way to reduce the size of the window without having corner textures collapsing on each other

## Todo
- "toolbarContainer" is not correctly aligned to the right (hardcoded width, won't work good with non-english locale)
- Some windows need to be move down a bit (templates, import, more?)
- Clean commented code
- Test on classic/tbc/....

2022-07-17 15:15 UTC, InfusOnWoW commented
I don't know how often minimize is used, so we can consider removing it. Anyway I trust stan and you to make it look good.

2022-07-18 23:41 UTC, Stanzilla commented
![ImABigFanFanGIF](https://user-images.githubusercontent.com/75278/179634825-1edad7e9-7f52-4cef-a9c1-f9e7ece3a562.gif)

2022-09-17 12:29 UTC, mrbuds commented
Rebased on dragonflight branch

![image](https://user-images.githubusercontent.com/189656/190856778-6aa4db5a-3ea3-49eb-ab21-ba8fb6bd5607.png)

I'd like to investigate in this branch changes to make it look more like 10.0

2023-04-22 23:08 UTC, Stanzilla requested changes
- on the code editor screen, can you make the "Help" button also use a popup to copy instead of the inline text?
- snippets panel could get the new border texture as well

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasLoadedHeaderButton.lua
File needs minor bump

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua
File needs minor bump

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasToolbarButton.lua
File needs minor bump

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/OptionsFrames/OptionsFrame.lua
> +    frame:SetWidth(odb.frame and odb.frame.width or defaultWidth)
As discussed on Discord, I think it looks better with the previous behavior because then the frame does not jump around

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/OptionsFrames/OptionsFrame.lua
> +    frame:SetWidth(160)
See above

2023-04-22 23:08 UTC, Stanzilla commented on WeakAurasOptions/WeakAurasOptions.toc
> +AceGUI-Widgets\AceGUIContainer-WeakAurasDropDownGroup.lua
Can be removed

2023-04-22 23:13 UTC, Stanzilla commented
We should talk about ditching the "Import" button in the header bar:

1) We already have import listed on the "New Aura" page
2) If we deemphasize the faster way to import, more people might notice the Premade Auras section at the top?

The icon picker needs something that tells the user that they need to search to see stuff, a placeholder text in the middle that says "Type to search" and maybe auto focus the search bar when you open it?

2023-04-22 23:44 UTC, InfusOnWoW commented
> We should talk about ditching the "Import" button in the header bar:

Well my original plan was to eventually get rid of the "Import" in the New Aura screen.

I think we could actually make the icon screen show icons by default. Just needs some coding. We after all made the atlas list show all atlases.

2023-04-22 23:53 UTC, Stanzilla commented
> > We should talk about ditching the "Import" button in the header bar:
> 
> Well my original plan was to eventually get rid of the "Import" in the New Aura screen.
> 
> I think we could actually make the icon screen show icons by default. Just needs some coding. We after all made the atlas list show all atlases.

Removing it there could work as well. Then we can make both header items a red button.

2023-04-23 17:13 UTC, mrbuds commented
> we can make both header items a red button.

Like that? Not sure i understand what you have in mind

![image](https://user-images.githubusercontent.com/189656/233854398-5f3b7d33-df0d-43c1-8d3a-59043d4e6fb4.png)

2023-04-23 17:15 UTC, Stanzilla commented
> > we can make both header items a red button.
> 
> Like that? Not sure i understand what you have in mind
> 
> ![image](https://user-images.githubusercontent.com/189656/233854398-5f3b7d33-df0d-43c1-8d3a-59043d4e6fb4.png)

yup

2023-04-23 17:35 UTC, InfusOnWoW commented
Are you sure you want red buttons?

2023-04-23 17:38 UTC, mrbuds commented
it looks like that without the added texture 
![image](https://user-images.githubusercontent.com/189656/233855630-ed2eed1a-abb1-4d34-b196-7c54b49bed20.png)
adding those textures require new ace widget

2023-04-23 17:44 UTC, InfusOnWoW commented
That's ugly, please no.

2023-04-23 17:51 UTC, Stanzilla commented
> adding those textures require new ace widget

Which texture?

2023-04-23 17:53 UTC, mrbuds commented
> > adding those textures require new ace widget
> 
> Which texture?

![image](https://user-images.githubusercontent.com/189656/233856456-0951d057-33b8-493c-b25c-c4302a5b8fac.png)

left of text

2023-04-23 17:53 UTC, mrbuds commented
And yeah i agree it's ugly

2023-04-23 18:08 UTC, Stanzilla commented
Ah those, okay then. Well if you both think it's ugly then leave it for now.

2023-04-24 18:37 UTC, Stanzilla approved these changes

2023-04-24 18:48 UTC, merged