add bar.paused checks to BigWigs_PauseBar and BigWigs_ResumeBar in or…
WeakAuras/WeakAuras2 pull request #3887
Opened 2022-10-18 16:31 UTC by Ironii

…der to avoid resetting bars when they are called twice in a row

add bwIsCd to bar and state values

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Tested on retail,  9.2.7

## Checklist

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-10-20 21:34 UTC, mrbuds requested changes

2022-10-20 21:34 UTC, mrbuds commented on WeakAuras/GenericTrigger.lua
> +      bar.bwIsCd = cd
I think `bwIsCd` is not good name for this field, i'd suggest `isCooldown` instead
From bigwigs source i see value could be true/false/nil, can you make the value only boolean?
Can you add it as a filter for the trigger, and a also as a condition?

2022-10-20 21:34 UTC, mrbuds commented on WeakAuras/GenericTrigger.lua
> +        WeakAuras.ScanEvents("BigWigs_PauseBar", text)
ScanEvents is called twice, looks like an overlook

2022-10-20 21:34 UTC, mrbuds commented on WeakAuras/GenericTrigger.lua
> +
luacheck warning to fix

2022-10-30 01:18 UTC, Ironii commented
requires squashing by someone else

2022-10-30 01:29 UTC, mrbuds approved these changes

2022-10-30 17:34 UTC, merged

2022-10-30 17:35 UTC, InfusOnWoW commented
I split up the commits and cleaned up the commit messages. It's the exact same code.